--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Kingbobs/casino
build-by-default: true
branches:
- master
projects:
  casino:
     libs:
      - format: virion
        vendor: poggit-project
        src: PJZ9n/FormAPI/libFormAPI
        version: 1.3.0
      - format: virion
        vendor: poggit-project
        src: poggit/libasynql/libasynql
        version: 3.3.0
...
