---
#編集しないでください
config-version: 1

#経済APIの設定
moneyapi:
  #EconomyAPI, MoneySytem, MixCoinSystemが使用できます。
  use: null

# ゲームの設定
games:
  # ゲーム名
  starslot:
    # 作成する数
    make-number: 5
    # 必要な金額
    cost: 100

# データベースの設定
database:
  # 現在sqliteのみ使用できます
  type: sqlite
  sqlite:
    # sqliteのファイル名
    file: data.db
...